name: CI

on:
  push:
    branches:
      - ci-test

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up git repository
        uses: actions/checkout@v4

      - name: generate docs
        run: |
          sudo apt-get install graphviz
          pip install -e .[dev]
          make docs MYPY_FLAGS=--no-install-types

      - name: deploy pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/sphinx/build/html
          branch: gh-pages
